name: Node.js CI

on: [push, pull_request, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme sphinxcontrib-openapi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          sphinx-build -b html docs docs/_build
      - name: Pushes to another repository
        uses: thebrainchain/copy-folder-action@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "docs/_build"
          output-directory: "meshdocs"
          destination-github-username: "cronelab"
          destination-repository-name: "ReconstructionVisualizer"
          user-email: c.coogan2201@gmail.com
      - name: Push to docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: neuroseek/3d_reconstruction
          tags: latest